### ISSUE TITLE
[macOS] mupen64plus doesn't work right for me

### ISSUE THREAD

**Issue by StenApp** [m64p/mupen64plus-GLideN64#38] opened 2017-11-23 18:12 UTC
I'm disappointed of mupen64plus, it doesn't work for me.
I run High Sierra on a MacBook Pro with a Radeon Pro 560, it supports OpenGL 4.1.
I tested GlideN64 and Angrylions, same problem:
Small picture in window down left, which pops up to window size.
The logos rendered half out of side. 
I see the top of the logo rotating down in the window.
<img width="912" alt="bildschirmfoto 2017-11-23 um 19 11 07" src="https://user-images.githubusercontent.com/32524257/33185346-2e8e9c24-d082-11e7-8010-ed42a747e1c2.png">
![broken](https://user-images.githubusercontent.com/32524257/33185347-2eb68d56-d082-11e7-805d-99c7e2bab52d.png)

**Comment by loganmc10** [comment] 2017-11-23 18:20
duplicate of https://github.com/m64p/mupen64plus-gui/issues/33

**Closed by loganmc10** 2017-11-23 18:20 UTC

**Comment by loganmc10** [comment] 2017-11-23 18:36
Mac isn't officially supported. I don't have a Mac, there is no way for me to fix this problem. Unless someone with a Mac develops a solution, it's not going to be fixed.
