### ISSUE TITLE
Linux/Intel iGPU: Blast Corps "Stage Select" lines flipped horizontally at higher resolutions

### ISSUE THREAD

**Issue by Pixelnarium** [m64p/mupen64plus-GLideN64#69] opened 2018-04-06 09:39 UTC
I really don't know where to start reporting this so I start here.

Like the title says. Tried the USA (Rev A) rom in m64p (downloaded today) in Linux on an Intel GPU. I clicked "Reset all the settings" and just changed the resolution.

It does **not** happen when using LLVMpipe (by using LIBGL_ALWAYS_SOFTWARE=1 env) so it could be a bug in the Intel driver. But the Intel driver is at OpenGL 4.5 while LLVMpipe is at OpenGL 3.3. So it could be also a bug in m64p/GlideN64?

1152x864 and lower works (screenshot is 1024x768)
![bc_1024_768](https://user-images.githubusercontent.com/30435935/38413422-e3c91250-398b-11e8-8ca9-f508a10621ad.png)

1280x960 and up does not work
![bc_1280_960](https://user-images.githubusercontent.com/30435935/38413424-e3eb0a5e-398b-11e8-8194-5db4b60e352a.png)

**Comment by loganmc10** [comment] 2018-04-06 15:39
Yes this is a bug with GLideN64, almost certainly the same as this bug: https://github.com/gonetz/GLideN64/issues/1725

I have identified the cause of the bug, and hopefully gonetz will be able to fix the issue. I'll close this and it's an issue with GLideN64, you can follow that bug report for updates.

**Closed by loganmc10** 2018-04-06 15:39 UTC
