### ISSUE TITLE
Mouse not working

### ISSUE THREAD

**Issue by kurioz** [m64p/mupen64plus-GLideN64#23] opened 2017-10-16 20:52 UTC
Is it possible to use the mouse?
I tried under the confic to set the mouse parameter to true but it does not work.

**Comment by loganmc10** [comment] 2017-10-16 20:58
No, the mouse is not currently supported, although it seems like there may be a third party tool that can handle it, hopefully I'll get around to adding mouse support in the future.

Here is the currently open issue: https://github.com/m64p/mupen64plus-gui/issues/28

I'll close this one since it's a duplicate of that issue

**Closed by loganmc10** 2017-10-16 20:58 UTC
